### ISSUE TITLE
On clicking on asset, user is redirected to Oxford Maths home page

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#127] opened 2016-03-09 06:26 UTC
Login to Student page using this credentials.
Username: Student5
Password: OUPMath@769

Go to My Tasks.

On clicking on the asset tile/Lesson/OH, user is redirected to Oxford Maths home page in a new tab.

![image](https://cloud.githubusercontent.com/assets/16831474/13627061/9263c8b8-e5ed-11e5-9282-8218ee699b56.png)

**Comment by manasghosh81** [comment] 2016-03-09 06:48
@madhumitadey : This is working absolutely fine for us in UAT. please clear the cache and try again. If done, please close this defect.

**Comment by somabanerjee** [comment] 2016-03-09 08:45
Hi Manas! I too have tried this and faced a similar problem. 

@mayank2k2 : Could you please ascertain whether this is a cache issue?

Thanks, 
Soma

**Comment by manasghosh81** [comment] 2016-03-09 17:26
@somabanerjee 
I can see from database there is multiple task with same chapter and topic.The screenshot you have given 4 ongoing task.But I am able to see only 3 tasks.This might be data issue or 

can you please let us know the exac

t steps to reproduce this issue or try the same chapter/topic with different student.

I can launch the other homework also from this student login but not this one.
![oh_issue](https://cloud.githubusercontent.com/assets/12447431/13644107/158cd214-e64a-11e5-94bd-ed13e21f80ea.png)

**Comment by somabanerjee** [comment] 2016-03-10 04:51
@manasghosh81 Since the task has lapsed today, we are unable to reproduce this error. We are re-assigning this task and  will see if we can reproduce this error to be shared with you.

**Closed as completed** 2016-03-11 05:41 UTC
Labels: Critical
